# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    api_key: '%env(REVOLUT_API_KEY)%'
    endpoint: '%env(REVOLUT_ENDPOINT)%'

services:
    Ramsey\Uuid\Validator\GenericValidator: ~
    App\Service\DatabaseService: ~
    App\Service\AuthenticationService: ~
    App\Enum\RolesEnum: ~
    App\Security\LoginSuccessHandler:
        autowire: true
        autoconfigure: true
    App\Controller\AuthController:
        arguments:
            $jwtManager: '@lexik_jwt_authentication.jwt_manager'
        tags: ['controller.service_arguments']
    App\Service\RevolutService:
        arguments:
            $apiKey: '%api_key%'
            $endpoint: '%endpoint%'

    # App\EventListener\AccessMiddleware:
    #     tags:
    #         - { name: kernel.event_listener, event: kernel.request, method: isAuthorizedRequest,  priority: 10 }
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
