# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    paypal_secret: '%env(PAYPAL_SECRET)%'
    paypal_client_id: '%env(PAYPAL_CLIENT_ID)%'
    paypal_access_token: '%env(PAYPAL_ACCCESS_TOKEN)%'
    paypal_orders: '%env(PAYPAL_ORDERS)%'
    aws_bucket_name: '%env(AWS_BUCKET_NAME)%'
    aws_access_key_id: '%env(AWS_ACCESS_KEY_ID)%'
    aws_secret_access_key: '%env(AWS_SECRET_ACCESS_KEY)%'

services:
    Ramsey\Uuid\Validator\GenericValidator: ~
    App\Service\DatabaseService: ~
    App\Service\AuthenticationService: ~
    App\Enum\RolesEnum: ~
    App\Security\LoginSuccessHandler:
        autowire: true
        autoconfigure: true
    App\Controller\AuthController:
        arguments:
            $jwtManager: '@lexik_jwt_authentication.jwt_manager'
        tags: ['controller.service_arguments']
    App\Service\PaypalService: ~
    App\Service\UploadService: ~

    # App\EventListener\AccessMiddleware:
    #     tags:
    #         - { name: kernel.event_listener, event: kernel.request, method: isAuthorizedRequest,  priority: 10 }
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $paypalSecret: '%paypal_secret%'
            string $paypalClientId: '%paypal_client_id%'
            string $paypalAccessToken: '%paypal_access_token%'
            string $paypalOrders: '%paypal_orders%'
            string $awsBucket: '%aws_bucket_name%'
            string $awsKeyId: '%aws_access_key_id%'
            string $awsSecretKey: '%aws_secret_access_key%'
    # Automatically registers your services as commands, event subscribers, etc.
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
